dist: bionic

language: python

python: 3.7

services:
  - docker

branches:
  only:
    - master
    # tags with 1.1.1
    - /^\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: Run tests
      name: Docker-compose with PostGIS database
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./exec.sh

    - stage: Run tests
      name: Fresh install versus migrations
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./install_migrate_generate.sh
#      after_success:
#        - ./schemaspy.sh
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: ${GH_TOKEN}
#        keep_history: true
#        on:
#          branch: master

    - stage: Deploy
      if: tag IS present
      name: Create release
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      before_deploy:
        - export RELEASE_TITLE="$TRAVIS_TAG"
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          api_key: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --create-plugin-repo
          on:
            tags: true
