# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GestionAdresse
                                 A QGIS plugin
 Create SQL intersect Table
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-02-12
        copyright            : (C) 2019 by 3Liz
        email                : info@3liz.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = '3Liz'
__date__ = '2019-02-12'
__copyright__ = '(C) 2019 by 3Liz'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerIntersecter class from file LayerIntersecter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Gestion_Adresse import GestionAdressePlugin
    return GestionAdressePlugin(iface)
