version: '3'

networks:
  adress_network:

services:
  db:
    image: kartoza/postgis:9.6-2.4
    hostname: db
    container_name: postgis
    networks:
      adress_network:
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=gis
      # Uncomment to expose the postgis database on the network
      # - ALLOW_IP_RANGE= 0.0.0.0/0
    # Uncomment to use the postgis database from outside the docker network
    # ports:
    #  - "35432:5432"
    healthcheck:
      test: "exit 0"

  qgis:
    image: qgis/qgis:release-3_4
    container_name: qgis
    networks:
      adress_network:
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ../gestion_base_adresse:/tests_directory/gestion_base_adresse
    environment:
      # - DISPLAY=unix$DISPLAY
      - DISPLAY=:99
